### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by malele4th** [seznam/elasticlient#11]
make error

/usr/bin/ld: not found -lgtest

collect2:error: ld returned 1 exit status

**Comment by johniez** [comment]
Well, you are missing Google Test. How did you build it? Did you use the `-DUSE_ALL_SYSTEM_LIBS=YES` or `-DUSE_SYSTEM_GTEST=YES` flags?

**Comment by adrianfime27** [comment]
I have the same error

**Comment by mbumba** [comment]
Hello @adrianfime27, 
as I can see you are using configuration options for use system version of dependencies. But it seems that `JsonCpp` library was not found (`/usr/bin/ld: no se puede encontrar -ljsoncpp_lib`). You can use options: `-DUSE_ALL_SYSTEM_LIBS=NO -DUSE_SYSTEM_JSONCPP=NO` which should force to build `JsonCpp` library from submodule instead.

**Comment by adrianfime27** [comment]
Thaks @mbumba, but i can't finish the make, the progress break in the 73%, look at this:
`[ 73%] Linking CXX executable ../bin/tests-elasticlient
CMakeFiles/tests-elasticlient.dir/tests-elasticlient.cc.o: En la función `__static_initialization_and_destruction_0(int, int) [clone .constprop.197]':
/media/adrian/25a829d6-fe0b-4096-944d-8bc99e8ea900/trazabilidadPD/elasticlient/test/tests-elasticlient.cc:215: referencia a `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)' sin definir
/media/adrian/25a829d6-fe0b-4096-944d-8bc99e8ea900/trazabilidadPD/elasticlient/test/tests-elasticlient.cc:221: referencia a `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)' sin definir
/media/adrian/25a829d6-fe0b-4096-944d-8bc99e8ea900/trazabilidadPD/elasticlient/test/tests-elasticlient.cc:234: referencia a `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)' sin definir
/media/adrian/25a829d6-fe0b-4096-944d-8bc99e8ea900/trazabilidadPD/elasticlient/test/tests-elasticlient.cc:242: referencia a `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)' sin definir
/media/adrian/25a829d6-fe0b-4096-944d-8bc99e8ea900/trazabilidadPD/elasticlient/test/tests-elasticlient.cc:251: referencia a `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)' sin definir
CMakeFiles/tests-elasticlient.dir/tests-elasticlient.cc.o:/media/adrian/25a829d6-fe0b-4096-944d-8bc99e8ea900/trazabilidadPD/elasticlient/test/tests-elasticlient.cc:259: más referencias a `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)' sin definir a continuación
collect2: error: ld returned 1 exit status
test/CMakeFiles/tests-elasticlient.dir/build.make:87: fallo en las instrucciones para el objetivo 'bin/tests-elasticlient'
make[2]: *** [bin/tests-elasticlient] Error 1
CMakeFiles/Makefile2:287: fallo en las instrucciones para el objetivo 'test/CMakeFiles/tests-elasticlient.dir/all'
make[1]: *** [test/CMakeFiles/tests-elasticlient.dir/all] Error 2
Makefile:140: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
`
