### ISSUE TITLE
fix(scroll): wrong payload on next batch

### ISSUE THREAD

**Issue by lyague** [seznam/elasticlient#13]
Dear maintainer(s),
it seems "scroll API" client does not meet elasticsearch expectations.

As described in https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html, "scroll_api" shall be a JSON param to provide in the payload.

However, the scroll lib "<elasticlient/scroll.h>" posts next scoll request using "scroll_id" directly in request body without encapsulating it in {"scroll_id": "VALUE"}.
Same case for clear function.

scroll.cc (changes):
```
diff --git a/src/scroll.cc b/src/scroll.cc
index c939c8d..685dcf0 100644
--- a/src/scroll.cc
+++ b/src/scroll.cc
@@ -183,7 +183,7 @@ bool Scroll::next(Json::Value &parsedResult) {
         std::ostringstream urlPart;
         urlPart << "_search/scroll?scroll=" << impl->scrollTimeout;
         LOG(LogLevel::INFO, "Scroll (next) on %s.", urlPart.str().c_str());
-        if (impl->run(urlPart.str(), scrollParameters.scrollId, parsedResult)) {
+        if (impl->run(urlPart.str(), "{\"scroll_id\": \"" + scrollParameters.scrollId + "\"}", parsedResult)) {
             return true;
         }
     }
@@ -202,7 +202,7 @@ void Scroll::clear() {
     } else {
         try {
             const cpr::Response r = impl->client->performRequest(
-                Client::HTTPMethod::DELETE, "_search/scroll/", scrollParameters.scrollId);
+                Client::HTTPMethod::DELETE, "_search/scroll", "{\"scroll_id\": \"" + scrollParameters.scrollId + "\"}");
             if (r.status_code / 100 != 2) {
                 LOG(LogLevel::WARNING, "Scroll delete failed response text: %s", r.text.c_str());
             }
```

This modification works fine for me.

Do not hesitate if you need more inputs / discuss's

Regards,
Laurent.

**Comment by mbumba** [comment]
Hello  Laurent,

thank you for reporting the issue. The Elasticsearch in current version did not support used Scroll syntax. We are gonna figure it out soon.

Martin

**Comment by lyague** [comment]
Hello Martin,
which ES version is compliant with elasticlient scroll API ?

Thx & regards,
Laurent.

**Comment by mbumba** [comment]
Hello lyague, 
at first sorry for really late response. Used syntax was supported until ES version 5.0. Now the issue should be fixed as I merged https://github.com/seznam/elasticlient/pull/17 to the master yesterday.

Martin
