### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by zlmink** [seznam/elasticlient#14]
Is there interest in adding the cpr async methods (e.g GetCallback)?  It appears all calls are blocking in this lib.  I have an event based async runtime that I'd like to add this libraries functionality on to, but it can't use blocking calls for HTTP requests given that they may take a few seconds to execute.  Thanks for your thoughts and this lib!

**Comment by johniez** [comment]
Hi, cpr async is using `std::async` to launch new thread and it does not reuse the session. So it can be probably solved (as a workaround) by calling std::async manually, if that is sufficient for you.
Due to that, I don't think we are interested in this kind of async.
