### ISSUE TITLE
Elasticlient ACID Transaction Support

### ISSUE THREAD

**Issue by onkarkolse** [seznam/elasticlient#19]
Can we achieve ACID transactional support using Elasticlient  (i.e.,  commit and rollback operations) .?
For eg :- when a document is added into a index which is in a transaction, we need to add/update the subset of that in the index for real time search. In case any error happens in table persist or elastic search index persist, the entire transaction should roll back. Is that case possible with Elasticlient .? If not, any other way to achieve this .?

**Comment by che0** [comment]
I don't believe Elasticsearch supports any transactions, as that would require distributing locks across many nodes in the cluster. If you need to synchronize across several indices, you need to handle this in your application.
