### ISSUE TITLE
Authentication Methods

### ISSUE THREAD

**Issue by zmink-pxc** [seznam/elasticlient#25]
Are there plans to support username/password / jwt authentication methods?

**Comment by johniez** [comment]
As we are using certificates to restrict access, these auth possibilities are now missing. It should not be hard to implement, I assume the appropriate header have to be set to [client session](https://github.com/seznam/elasticlient/blob/d68e30e382b5f2817be8cd901494736b26d4896e/src/client-impl.h#L42) from [constructor](https://github.com/seznam/elasticlient/blob/d68e30e382b5f2817be8cd901494736b26d4896e/include/elasticlient/client.h#L232) options.

We cannot promise implementing this soon, but we are happy to accept pull requests from others...

**Comment by zmink-pxc** [comment]
@johniez thanks for the response and feedback.  I'll give the library a shot and submit a PR if necessary.  SSL alone might be sufficient, but wanted to get your thoughts.  Thanks again
