### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by Denny007** [seznam/elasticlient#3]
Hi, when I run `cmake ..` in build, it appear error like this:
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MHD_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/src
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/src
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/src
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/src
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/src
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/src
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/src
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/src
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/test
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/test
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/test
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/test
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/test
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/test
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/test
   used as include directory in directory /data/denny/github/elasticlient/external/httpmockserver/test
MHD_LIBRARY (ADVANCED)
    linked by target "test-server" in directory /data/denny/github/elasticlient/external/httpmockserver/test
    linked by target "test-server" in directory /data/denny/github/elasticlient/external/httpmockserver/test
    linked by target "tests-elasticlient" in directory /data/denny/github/elasticlient/test
`

Could you tell me how to fix it, thank you

**Comment by Denny007** [comment]
OK, I know how to fix this
use `cmake -DBUILD_ELASTICLIENT_TESTS=NO ..` command

**Comment by che0** [comment]
I guess the issue is that you're building it with teststs, which require `httpmockserver`, which in turn requires `libmicrohttpd` which you probably don't have.
