### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by tlsqlgksthsu** [seznam/elasticlient#32]
Environment
- Windows 11 (OS build : 22000.795) - 64bit
- Visual Studio 2022
- CMake 3.23.3 (with gui)
- vcpkg ( installed on my PC : curl, openssl, zlib, boost, ... )

I did this :

1. README.md
    - step 1 >>> step 2 >> step 3 ( It's going well so far. )

2. [Pull Request Link](https://github.com/seznam/elasticlient/pull/26)

but, not build my solution. errors are

- Command line error D8021 : invalid numeric argument '/Wextra' -> when I tried no.2 (pull request)

- [c4430 error](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-c4430?f1url=%3FappId%3DDev16IDEF1%26l%3DKO-KR%26k%3Dk(C4430)%26rd%3Dtrue&view=msvc-170) ( If I erase /wextra from the build option, c4430 appears countless times, resulting in c1003. )

**Comment by che0** [comment]
I don't think we have ever tested this on Visual Studio compiler. For it to work I guess you would at least have to add something like `if(MSVC) ...` to CMakeLists.txt and then change CMAKE_CXX_FLAGS* variables to those than Visual Studio accepts.

**Comment by tlsqlgksthsu** [comment]
Thanks!
