### ISSUE TITLE
Could NOT find HTTPMOCKSERVER

### ISSUE THREAD

**Issue by vlaicu95** [seznam/elasticlient#6]
I have followed every step from the README file but I get the following error:

cmake -DUSE_ALL_SYSTEM_LIBS=YES ..
-- Checking compiler C++11 support.
--   ELASTICLIENT_VERSION_MAJOR: 2
--   ELASTICLIENT_VERSION_MINOR: 1
--   ELASTICLIENT_VERSION_PATCH: 0
--   BUILD_ELASTICLIENT_TESTS: ON
--   BUILD_ELASTICLIENT_EXAMPLE: ON
--   USE_ALL_SYSTEM_LIBS: YES
-- CMAKE_MODULE_PATH: /home/vlaicu/ELASTIC_TEST/elasticlient/cmake/Modules/
-- Could NOT find HTTPMOCKSERVER (missing:  HTTPMOCKSERVER_LIBRARY HTTPMOCKSERVER_INCLUDE_DIR) 
CMake Error at external/CMakeLists.txt:8 (message):
  HTTPMockServer library not found.

-- Configuring incomplete, errors occurred!

I have also done step 2: git submodule update --init --recursive

**Comment by che0** [comment]
When you set `-DUSE_ALL_SYSTEM_LIBS=YES` it tells the build to use system HTTPMockServer. If you don't have this library in your system, you need to set `-DUSE_ALL_SYSTEM_LIBS=NO`.

**Comment by vlaicu95** [comment]
Isn't git submodule update --init --recursive getting all of the required dependencies under elasticclient/external + cpr, googletest,httmockerserver,jsoncpp ?

**Comment by che0** [comment]
Yes, it downloads sources for all those dependencies. `-DUSE_ALL_SYSTEM_LIBS=YES` then tells cmake you don't want to use them.

**Comment by vlaicu95** [comment]
Sry my bad. I understood that -DUSE_ALL_SYSTEM_LIBS=YES tells cmake to use them.
Tank you.
